language: node_js
node_js:
  - 0.10
notifications:
  email:
    on_success: always
before_script:
  - npm install grunt-cli -g
before_deploy:
  - "grunt prod"
  - "ls | grep -v 'dist' | xargs rm -rf"
  - echo "Adding refs/heads/master for Azure deployment to work"
  - git checkout --no-track -b master || true
  - git show-ref
deploy:
  provider: azure_web_apps
  skip_cleanup: true
  verbose: true
