language: node_js
node_js:
  - 0.10
notifications:
  email:
    on_success: always
before_script:
  - npm install grunt-cli -g
before_deploy:
  - "grunt prod"
  - "ls | grep -v 'dist' | xargs rm -rf"
  - "git checkout HEAD"
  - "git add . --all --force"
  - "git commit -m \"Skip Cleanup Commit\""
deploy:
  provider: azure_web_apps
  skip_cleanup: true
  verbose: true
