language: node_js
node_js:
  - 0.10
notifications:
  email:
    on_success: always
before_deploy: "grunt prod"
deploy:
  provider: azure_web_apps
  username: azure_deployment_user       # If AZURE_WA_USERNAME isn't set
  password: azure_deployment_password   # If AZURE_WA_PASSWORD isn't set
  site: azure_deployment_sitename       # If AZURE_WA_SITE isn't set
