language: node_js
node_js:
  - 0.10
notifications:
  email:
    on_success: always
before_script:
  - npm install grunt-cli -g
before_deploy:
  - "grunt prod"
  - "ls | grep -v 'dist' | xargs rm -rf"
  - "git config --global user.email 'adrian.jagusch@uni-oldenburg.de'"
  - "git config --global user.name 'Adrian Jagusch'"
  - "git checkout HEAD"
  - "git add . --all --force"
  - "git commit -m \"Skip Cleanup Commit\""
  - "git push --force --quiet https://$AZURE_WA_USERNAME:$AZURE_WA_PASSWORD@$AZURE_WA_SITE.scm.azurewebsites.net:443/$AZURE_WA_SITE.git HEAD:master"
deploy:
  provider: azure_web_apps
  skip_cleanup: true
  verbose: true
